# Generated by Django 5.0.7 on 2024-08-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("body", models.TextField(verbose_name="내용")),
                (
                    "sub_title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="부제목"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, default="", verbose_name="이미지 URL"),
                ),
            ],
            options={
                "verbose_name": "콘텐츠",
                "db_table": "content",
            },
        ),
    ]
