# Generated by Django 5.0.7 on 2024-08-06 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_contentcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50, verbose_name="태그")),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_tags",
                        to="content.content",
                        verbose_name="콘텐츠",
                    ),
                ),
            ],
            options={
                "verbose_name": "콘텐츠 태그",
                "verbose_name_plural": "콘텐츠 태그",
                "db_table": "content_tag",
            },
        ),
    ]
