# Generated by Django 5.0.7 on 2024-08-07 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_contenttag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="author",
        ),
        migrations.AddField(
            model_name="content",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자 ID",
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
