# Generated by Django 5.0.7 on 2024-08-07 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_content_author_content_user_delete_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자 ID",
            ),
        ),
    ]
