# Generated by Django 5.0.7 on 2024-08-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_contentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="like_count",
            field=models.IntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.AddField(
            model_name="content",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="조회 수"),
        ),
    ]
